name: map_practice
channels:
- conda-forge
- defaults
dependencies:
- python-annoy=1.10.0=py36_0
- boto=2.48.0=py36_0
- bz2file=0.98=py36_0
- certifi=2016.2.28=py36_0
- gensim
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- requests=2.14.2=py36_0
- scikit-learn=0.19.0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- six=1.10.0=py36_0
- smart_open=1.5.3=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- ujson=1.35=py36_0
- wheel=0.29.0=py36_0
- word2vec=0.9.1=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pandas=0.20.3
- pip:
  - annoy==1.10.0
  - click==6.7
  - python-dotenv==0.7.1
  - smart-open==1.5.3
  - toolz==0.8.2
  - qds-sdk
